# name: Build and Deploy
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout ğŸ›ï¸
#         uses: actions/checkout@v3
#       - uses: actions/setup-node@v1
#         with:
#           node-version: '18'
#       - name: Clear npm cache
#         run: npm cache clean -f
#       - uses: actions/cache@v2
#         with:
#           path: ~/.npm
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-
#       - name: Install and Build ğŸ”§
#         run: |
#           npm ci
#           npm run build ngx-obelisco-v17-demo --configuration production
#       - name: Deploy ğŸš€
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           GITHUB_TOKEN: ${{ secrets.GH_ANGULAR_TOKEN }}
#           branch: gh-pages
#           folder: ./dist/ngx-obelisco-v17